export const OVERALL_DATA_REQUEST = 'DATA/OVERALL_DATA_REQUEST';
export const OVERALL_DATA_ERROR = 'DATA/OVERALL_DATA_ERROR';
export const OVERALL_DATA_SUCCESS = 'DATA/OVERALL_DATA_SUCCESS';
export const LISTING_DATA_UPDATE = 'DATA/LISTING_DATA_UPDATE';
export const OVERALL_DATA_PAGE_NO = 'DATA/OVERALL_DATA_PAGE_NO';
export const LISTING_DATA_PAGE_NO = 'DATA/LISTING_DATA_PAGE_NO';